version: "3.9"
services:
  app:
    image: gotodo
    build:
      args:
        - targer=dev
    environment:
      TODO_ENV: dev
      PORT: 8080
      TODO_DB_HOST: todo-db
      TODO_DB_USER: todo
      TODO_DB_PORT: 5432
      TODO_DB_PASSWORD: todo
      TODO_DB_DATABASE: todo
    volumes:
      - .:/app
    ports:
      - "18000:8080"
  todo-db:
    image: postgres:14-alpine
    container_name: todo-db
    environment:
      POSTGRES_PASSWORD: todo
      POSTGRES_USER: todo
      POSTGRES_DB: todo
    volumes:
      - todo-db-data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
volumes:
  todo-db-data:
