CREATE TABLE "user" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) UNIQUE NOT NULL,
  "password" varchar(80) NOT NULL,
  "role" varchar(80) NOT NULL,
  "created" datetime(6) NOT NULL,
  "modified" datetime(6) NOT NULL
);

CREATE TABLE "task" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(128) NOT NULL,
  "status" varchar(20) NOT NULL,
  "created" datetime(6) NOT NULL,
  "modified" datetime(6) NOT NULL
);
